[package]
name = "worley-particle"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
image = "0.25.5"
tiny-skia = "0.11.4"

[dependencies]
contour = "0.13.1"
flatbuffers = "25.2.10"
rand = "0.8.5"
thiserror = "2.0.9"

[build-dependencies]
flatc-rust = "0.2.0"
